service: uashdkuahda

frameworkVersion: '2 || 3'


provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-2
  lambdaHashingVersion: 20201221
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - s3:*
        - cognito-identity:*
        - cognito-sync:*
        - cognito-idp:*
        - ssm:GetParameter
      Resource:
        - arn:aws:dynamodb:us-east-2:666398651410:table/kashliatskyi-columns
        - arn:aws:dynamodb:us-east-2:666398651410:table/kashliatskyi-card
        - arn:aws:cognito-idp:us-east-2:666398651410:userpool/us-east-2_HYPeBfIpZ
        - arn:aws:s3:::maks-trello-files/*

resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'

functions:
  healthCheck:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
          cors: true

  allColumn:
    handler: src/сontrollers/columnController.allColumn
    events:
      - http:
          path: columns
          method: get
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:us-east-2:666398651410:userpool/us-east-2_HYPeBfIpZ

  createColumn:
    handler: src/сontrollers/columnController.createColumn
    events:
      - http:
          path: createColumn
          method: post
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:us-east-2:666398651410:userpool/us-east-2_HYPeBfIpZ

  deleteColumn:
    handler: src/сontrollers/columnController.deleteColumn
    events:
      - http:
          path: deleteCol/{id}
          method: delete
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:us-east-2:666398651410:userpool/us-east-2_HYPeBfIpZ

  updateColumn:
    handler: src/сontrollers/columnController.updateColumn
    events:
      - http:
          path: updateCol/{id}
          method: put
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:us-east-2:666398651410:userpool/us-east-2_HYPeBfIpZ

  allCards:
    handler: src/сontrollers/cardsController.allCards
    events:
      - http:
          path: cards
          method: get
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:us-east-2:666398651410:userpool/us-east-2_HYPeBfIpZ

  createCard:
    handler: src/сontrollers/cardsController.createCard
    events:
      - http:
          path: createCard
          method: post
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:us-east-2:666398651410:userpool/us-east-2_HYPeBfIpZ

  deleteCard:
    handler: src/сontrollers/cardsController.deleteCard
    events:
      - http:
          path: deleteCard/{id}
          method: delete
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:us-east-2:666398651410:userpool/us-east-2_HYPeBfIpZ

  updateCard:
    handler: src/сontrollers/cardsController.updateCard
    events:
      - http:
          path: updateCard/{id}
          method: put
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:us-east-2:666398651410:userpool/us-east-2_HYPeBfIpZ


  signIn:
    handler: src/cognito/cognitoController.signIn
    environment:
      CLIENT_ID: ${ssm:/MAKS_COGNITO_CLIENT_ID}
      USER_POOL_ID: ${ssm:/MAKS_COGNITO_USER_POOL_ID}
    events:
      - http:
          path: signIn
          method: post
          cors: true

  signUp:
    handler: src/cognito/cognitoController.signUp
    environment:
      CLIENT_ID: ${ssm:/MAKS_COGNITO_CLIENT_ID}
      USER_POOL_ID: ${ssm:/MAKS_COGNITO_USER_POOL_ID}
    events:
      - http:
          path: signUp
          method: post
          cors: true

  logout:
    handler: src/cognito/cognitoController.logout
    environment:
      CLIENT_ID: ${ssm:/MAKS_COGNITO_CLIENT_ID}
      USER_POOL_ID: ${ssm:/MAKS_COGNITO_USER_POOL_ID}
    events:
      - http:
          path: logout
          method: post
          cors: true

  refresh:
    handler: src/cognito/cognitoController.refresh
    environment:
      CLIENT_ID: ${ssm:/MAKS_COGNITO_CLIENT_ID}
      USER_POOL_ID: ${ssm:/MAKS_COGNITO_USER_POOL_ID}
    events:
      - http:
          path: refresh
          method: post
          cors: true


  getS3Object:
    handler: src/s3/s3Controller.getObject
    events:
      - http:
          path: getObject
          method: post
          cors: true

  putS3Object:
    handler: src/s3/s3Controller.putObject
    events:
      - http:
          path: putObject
          method: post
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:us-east-2:666398651410:userpool/us-east-2_HYPeBfIpZ


  deleteS3Object:
    handler: src/s3/s3Controller.deleteFile
    events:
      - http:
          path: deleteObject
          method: post
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:us-east-2:666398651410:userpool/us-east-2_HYPeBfIpZ



plugins:
  - serverless-offline
